import "server-only";

import type { Json } from "@/types/database";
import { getOrgName } from "@/lib/auth/org";
import { getOrgSettings } from "@/lib/settings/org-settings";
import {
  createInterviewSession,
  type InterviewSession,
} from "@/lib/voice-agent/session-service";
import type {
  ResearchBrand,
  ResearchInput,
} from "@/lib/voice-agent/interviewer";
import { createResearchSupabase } from "./db";
import { getResearchPlan, planToAgentContext } from "./plans-service";
import { getResearchInvite } from "./scheduling";

/**
 * Orchestration for the research flow.
 *
 * createResearchInterview is analog to createAndInviteCheckin but WITHOUT an
 * email send. It loads the plan, builds the agent's input bucket (plan
 * context + optional brand context derived from the org), and creates the
 * interview_sessions row via createInterviewSession (which fires the opening
 * message itself). The mail layer + scheduled-slot flow live in the sibling
 * milestone — today we just produce a token so /interview/[token] is
 * reachable for a manual smoke test.
 *
 * The transcript-side handler (persistResearchTranscriptAndDiscovery) lives
 * in transcript-service.ts to break the import cycle with session-service.
 */

// ── createResearchInterview ────────────────────────────────────────────────

export type CreateResearchInterviewStatus =
  | "created"
  | "plan_not_found"
  | "invite_not_found"
  | "invite_missing_token"
  | "error";

export interface CreateResearchInterviewResult {
  status: CreateResearchInterviewStatus;
  /** Public capability token for /interview/[token]. */
  accessToken: string | null;
  sessionId: string | null;
  /**
   * The freshly inserted session row, present when status === 'created'.
   * Threaded through verbatim from createInterviewSession's
   * `.insert().select().single()` return so callers can render the public
   * view WITHOUT a second DB read.
   *
   * Why this matters: getPublicSession's lazy-create path used to discard
   * this result and re-read via loadByToken(token). That re-read could
   * return null under cold-start latency (Anthropic Opus call front-loads
   * the function-time budget, the subsequent supabase-js GET can abort)
   * — surfacing as a first-hit 404 even though the row was committed.
   * By handing back the in-memory session we make the read-after-write
   * structurally unreachable for the happy path; the caller only needs a
   * loadByToken fallback for cross-request racers (different request hit
   * unique-violation on access_token → returns status='error' → fallback
   * read picks up the winner's row).
   */
  session: InterviewSession | null;
  message: string | null;
}

/**
 * Create a research interview SESSION (with opening message generated by
 * nextResearchMessage).
 *
 * TOKEN CONTRACT (merge of proactive ↔ scheduling): the access_token is
 * the participant's capability credential. Two valid origins:
 *
 *   (1) Invite-bound:  When `inviteId` is given, the invite must already
 *       carry an access_token (created earlier via createResearchInvite, so
 *       the scheduling mail has a stable URL to embed). The session is
 *       created with the SAME token — getPublicSession(token) then resolves
 *       to this session. Also mirrors a planId match so the session points
 *       at the same plan as the invite.
 *
 *   (2) Ad-hoc:  When `inviteId` is null/undefined (smoke test, one-off
 *       link, no scheduling), createInterviewSession generates a fresh
 *       token internally — original proactive behavior, unchanged.
 *
 * The session is created EAGERLY in both cases — opening message is fired
 * immediately so the participant gets a populated chat on first load. A
 * lazy variant (token on invite only, session built on first /interview/
 * [token] hit) is possible later if invite-create cost becomes a concern.
 */
export async function createResearchInterview(params: {
  orgId: string;
  planId: string;
  /** Optional invite link. When set, the invite's existing access_token is
   *  reused for the session (token contract above). */
  inviteId?: string | null;
  /** Override language; defaults to interviewer's DEFAULT_INTERVIEW_LANGUAGE. */
  language?: "de" | "en";
  /** Phase 4: screening answers of the qualified participant, persisted onto
   *  the created session. Omitted by the no-screening lazy path → null. */
  screeningAnswers?: Json | null;
  /** Phase 4 Baustein 2 (offener Studien-Link): the open-link row a qualified
   *  ANONYMOUS walk-in entered through. Additive, threaded verbatim onto the
   *  session's open_link_id (nullable attribution, mirrors invite_id). Set ONLY
   *  by the open-link screen route; null/omitted on every per-invite / ad-hoc
   *  call, so those stay byte-identical. The open path always passes
   *  inviteId: null + openLinkId → a FRESH session token is minted internally
   *  (the open-link token is shared and must NEVER become a session token). */
  openLinkId?: string | null;
  /** Phase 4 Baustein 3 (Panel-Anbieter) E1: Inbound-Attribution-Bucket
   *  (PanelContext-Form als Json), threaded verbatim onto the session's
   *  panel_context — EXAKT wie openLinkId/screeningAnswers. Set ONLY by the
   *  open-link screen route when a Prolific PID is present; null/omitted on every
   *  other call → byte-identisch. KEIN Provider-Call, KEIN Key (das wäre E3). */
  panelContext?: Json | null;
}): Promise<CreateResearchInterviewResult> {
  const base: CreateResearchInterviewResult = {
    status: "error",
    accessToken: null,
    sessionId: null,
    session: null,
    message: null,
  };

  const plan = await getResearchPlan(params.orgId, params.planId);
  if (!plan) {
    return {
      ...base,
      status: "plan_not_found",
      message: "Research plan not found in this organization.",
    };
  }

  // Resolve the invite-bound token (case 1) if an invite is given. Defer the
  // error returns until after the early validation so the route layer gets
  // precise statuses rather than a generic "error".
  let inviteAccessToken: string | undefined;
  if (params.inviteId) {
    const invite = await getResearchInvite(params.orgId, params.inviteId);
    if (!invite) {
      return {
        ...base,
        status: "invite_not_found",
        message: "Research invite not found in this organization.",
      };
    }
    if (!invite.access_token) {
      return {
        ...base,
        status: "invite_missing_token",
        message:
          "Invite has no access_token — create the invite via createResearchInvite first.",
      };
    }
    inviteAccessToken = invite.access_token;
  }

  try {
    // Brand context — best-effort. Org-name + product label give the agent
    // grounding ("when you set up new sales pipelines …") without naming
    // the product to the participant. Both lookups are .catch(() => null) so
    // missing settings don't break the session — the agent then frames itself
    // as independent research, exactly like the external path will.
    const [orgName, orgSettings] = await Promise.all([
      getOrgName(params.orgId).catch(() => null),
      getOrgSettings(params.orgId).catch(() => null),
    ]);
    const brand: ResearchBrand | null = orgName?.trim()
      ? {
          orgName: orgName.trim(),
          productName: orgSettings?.productName?.trim() || null,
        }
      : null;

    const input: ResearchInput = {
      plan: planToAgentContext(plan),
      brand,
    };

    const session: InterviewSession = await createInterviewSession({
      orgId: params.orgId,
      kind: "research",
      mode: "text",
      planId: plan.id,
      inviteId: params.inviteId ?? null,
      // Additive open-link attribution. Null on the invite/ad-hoc paths → no-op.
      openLinkId: params.openLinkId ?? null,
      // Additive panel attribution. Null on every non-panel path → the INSERT
      // never references the column (byte-identical). Threaded verbatim, mirrors
      // openLinkId/screeningAnswers.
      panelContext: params.panelContext ?? null,
      // Pass the invite-bound token through when present; otherwise
      // createInterviewSession generates a fresh one. On the open-link path
      // inviteAccessToken is undefined (inviteId is null) → a FRESH session
      // token is minted, never the shared open-link token.
      accessToken: inviteAccessToken,
      dealContext: input,
      language: params.language ?? "de",
      screeningAnswers: params.screeningAnswers ?? null,
      // Perf-Etappe B2: every createResearchInterview caller sits on the
      // PARTICIPANT's request path (lazy page-load create + both screening
      // routes). Create the row without the blocking Opus opening — the page
      // paints immediately and the opening arrives as the first streamed
      // turn (ensureOpeningTurn via /api/interview/[token]/stream).
      skipOpening: true,
    });

    // Thread the freshly inserted session through — getPublicSession's
    // lazy-create path uses this to render directly via toPublicView,
    // skipping the previously-fragile re-read via loadByToken(token).
    return {
      status: "created",
      accessToken: session.accessToken,
      sessionId: session.id,
      session,
      message: null,
    };
  } catch (err) {
    console.error(
      `[createResearchInterview] failed for plan ${params.planId}:`,
      err instanceof Error ? err.message : err,
    );
    if (err instanceof Error && err.cause !== undefined) {
      console.error("[createResearchInterview] underlying cause:", err.cause);
    }
    return {
      ...base,
      status: "error",
      message: "Could not create the research interview.",
    };
  }
}

// ── createResearchInvite ───────────────────────────────────────────────────
// Token-side of the merge: the scheduling branch (sendResearchInvite) needs
// research_invites.access_token populated BEFORE it can build the mail.
// This helper is the canonical creation path — it generates the 256-bit
// token and stores it on the invite row. The session itself is NOT created
// here; it lands later either eagerly (caller invokes createResearch-
// Interview right after) or lazily (a future /interview/[token] handler can
// resolve token → invite → session on first hit). For now we expose the
// eager path through this orchestration; lazy can be added without changing
// the token contract.

export interface CreateResearchInviteResult {
  status: "created" | "plan_not_found" | "error";
  inviteId: string | null;
  accessToken: string | null;
  message: string | null;
}

export async function createResearchInvite(params: {
  orgId: string;
  planId: string;
  contactLabel: string;
  contactEmail?: string | null;
  modePreference?: "text" | "voice" | "video";
}): Promise<CreateResearchInviteResult> {
  const plan = await getResearchPlan(params.orgId, params.planId);
  if (!plan) {
    return {
      status: "plan_not_found",
      inviteId: null,
      accessToken: null,
      message: "Research plan not found in this organization.",
    };
  }

  const supabase = createResearchSupabase();
  // 256-bit URL-safe token, same shape as session-service's generateToken().
  // Keeping the generation here (not via session-service.generateToken) keeps
  // session-service free of any research-invite dependency — the token is
  // just a string and either side may produce it.
  const { randomBytes } = await import("node:crypto");
  const accessToken = randomBytes(32).toString("base64url");

  const { data, error } = await supabase
    .from("research_invites")
    .insert({
      org_id: params.orgId,
      plan_id: plan.id,
      contact_label: params.contactLabel,
      contact_email: params.contactEmail ?? null,
      mode_preference: params.modePreference ?? "text",
      status: "pending",
      access_token: accessToken,
    })
    .select("id, access_token")
    .single();

  if (error || !data) {
    console.error(
      `[createResearchInvite] insert failed for plan ${params.planId}:`,
      error?.message ?? "no row returned",
    );
    return {
      status: "error",
      inviteId: null,
      accessToken: null,
      message: "Could not create the research invite.",
    };
  }

  return {
    status: "created",
    inviteId: data.id,
    accessToken: data.access_token,
    message: null,
  };
}

// persistResearchTranscriptAndDiscovery moved to ./transcript-service.ts to
// break the session-service ↔ research-orchestration import cycle. See that
// file's header comment.
