import type { Deal } from "./types";

/**
 * 10 realistic B2B SaaS demo deals.
 * Risk distribution (expected after classifier):
 *  - High/critical risk: deals 001, 003, 007
 *  - Medium risk:        deals 004, 005, 008, 009
 *  - Low risk:           deals 002, 006, 010
 */
export const MOCK_DEALS: Deal[] = [
  // === HIGH RISK 1: stalled DACH, multiple competitors ===
  {
    id: "deal_001",
    name: "Nordbank Enterprise — €85k ARR",
    companyName: "Nordbank GmbH",
    amount: 85000,
    currency: "EUR",
    stage: "negotiation",
    ownerName: "Sarah Mueller",
    championName: "Marcus Weber",
    championTitle: "CTO",
    daysSinceLastActivity: 14,
    callsCompleted: 8,
    emailsSent: 23,
    stakeholdersCount: 3,
    competitorsMentioned: ["Salesforce", "Hubspot"],
    closeDate: "2026-06-15",
    createdAt: "2026-03-10",
  },

  // === LOW RISK 1: clean late-stage USA deal ===
  {
    id: "deal_002",
    name: "TechCorp Renewal — $120k ARR",
    companyName: "TechCorp Inc.",
    amount: 120000,
    currency: "USD",
    stage: "verbal_commit",
    ownerName: "Mike Johnson",
    championName: "Lisa Chen",
    championTitle: "VP Engineering",
    daysSinceLastActivity: 2,
    callsCompleted: 12,
    emailsSent: 31,
    stakeholdersCount: 5,
    competitorsMentioned: [],
    closeDate: "2026-06-30",
    createdAt: "2026-02-15",
  },

  // === HIGH RISK 2: procurement stall, 3 competitors, close date imminent ===
  {
    id: "deal_003",
    name: "Bayrische Versicherung — €45k ARR",
    companyName: "Bayrische Versicherung AG",
    amount: 45000,
    currency: "EUR",
    stage: "proposal_sent",
    ownerName: "Thomas Becker",
    championName: "Anna Schmidt",
    championTitle: "Head of Procurement",
    daysSinceLastActivity: 22,
    callsCompleted: 5,
    emailsSent: 18,
    stakeholdersCount: 2,
    competitorsMentioned: ["Salesforce", "Microsoft Dynamics", "SAP"],
    closeDate: "2026-05-30",
    createdAt: "2026-02-01",
  },

  // === MEDIUM RISK 1: big USD deal, healthy but 1 competitor ===
  {
    id: "deal_004",
    name: "CloudCommerce Platform — $200k ARR",
    companyName: "CloudCommerce Inc.",
    amount: 200000,
    currency: "USD",
    stage: "negotiation",
    ownerName: "Rebecca Davis",
    championName: "James Park",
    championTitle: "COO",
    daysSinceLastActivity: 8,
    callsCompleted: 10,
    emailsSent: 28,
    stakeholdersCount: 4,
    competitorsMentioned: ["Hubspot"],
    closeDate: "2026-07-15",
    createdAt: "2026-03-01",
  },

  // === MEDIUM RISK 2: early-stage, 2 competitors, thin stakeholder coverage ===
  {
    id: "deal_005",
    name: "Helven Industries — €68k ARR",
    companyName: "Helven Industries GmbH",
    amount: 68000,
    currency: "EUR",
    stage: "qualified",
    ownerName: "Klaus Brandt",
    championName: "Petra Hoffmann",
    championTitle: "VP Sales",
    daysSinceLastActivity: 5,
    callsCompleted: 3,
    emailsSent: 12,
    stakeholdersCount: 2,
    competitorsMentioned: ["Gong", "Chorus"],
    closeDate: "2026-08-01",
    createdAt: "2026-04-15",
  },

  // === LOW RISK 2: small-but-clean late-stage deal ===
  {
    id: "deal_006",
    name: "Lattix Software — $35k ARR",
    companyName: "Lattix Inc.",
    amount: 35000,
    currency: "USD",
    stage: "verbal_commit",
    ownerName: "Jennifer Wu",
    championName: "David Park",
    championTitle: "CTO",
    daysSinceLastActivity: 1,
    callsCompleted: 8,
    emailsSent: 18,
    stakeholdersCount: 4,
    competitorsMentioned: [],
    closeDate: "2026-06-10",
    createdAt: "2026-03-20",
  },

  // === CRITICAL RISK: large deal, 4 competitors, CEO late-entry, stalling ===
  {
    id: "deal_007",
    name: "DACH Logistics — €175k ARR",
    companyName: "DACH Logistics AG",
    amount: 175000,
    currency: "EUR",
    stage: "negotiation",
    ownerName: "Hans Mueller",
    championName: "Lukas Vogel",
    championTitle: "CEO",
    daysSinceLastActivity: 18,
    callsCompleted: 15,
    emailsSent: 42,
    stakeholdersCount: 6,
    competitorsMentioned: ["Salesforce", "Pipedrive", "Zoho", "Microsoft Dynamics"],
    closeDate: "2026-06-01",
    createdAt: "2026-01-20",
  },

  // === MEDIUM RISK 3: proposal sent, 1 competitor, moderate stall ===
  {
    id: "deal_008",
    name: "RootSignal Tech — $58k ARR",
    companyName: "RootSignal Inc.",
    amount: 58000,
    currency: "USD",
    stage: "proposal_sent",
    ownerName: "Emily Chen",
    championName: "Robert Kim",
    championTitle: "Head of Operations",
    daysSinceLastActivity: 11,
    callsCompleted: 7,
    emailsSent: 19,
    stakeholdersCount: 3,
    competitorsMentioned: ["Hubspot"],
    closeDate: "2026-07-01",
    createdAt: "2026-03-15",
  },

  // === MEDIUM RISK 4: largest deal, 2 competitors but healthy activity ===
  {
    id: "deal_009",
    name: "SaaSCo Growth — $250k ARR",
    companyName: "SaaSCo Holdings",
    amount: 250000,
    currency: "USD",
    stage: "negotiation",
    ownerName: "Marcus Thompson",
    championName: "Sophie Martin",
    championTitle: "VP Product",
    daysSinceLastActivity: 6,
    callsCompleted: 14,
    emailsSent: 35,
    stakeholdersCount: 6,
    competitorsMentioned: ["Salesforce", "Hubspot"],
    closeDate: "2026-07-30",
    createdAt: "2026-02-10",
  },

  // === LOW RISK 3: small, clean, early-stage but healthy ===
  {
    id: "deal_010",
    name: "MunichSoft Starter — €15k ARR",
    companyName: "MunichSoft GmbH",
    amount: 15000,
    currency: "EUR",
    stage: "qualified",
    ownerName: "Christine Wagner",
    championName: "Felix Roth",
    championTitle: "CTO",
    daysSinceLastActivity: 3,
    callsCompleted: 2,
    emailsSent: 6,
    stakeholdersCount: 2,
    competitorsMentioned: [],
    closeDate: "2026-08-15",
    createdAt: "2026-04-25",
  },
];
