import "server-only";

import PDFDocument from "pdfkit";
import type { LossReportData } from "@/lib/loss/reports";
import type { ForecastSummary } from "@/lib/forecast/service";

// Findr branding — consistent with the dashboard color polish.
const COLORS = {
  primary: "#6366f1", // indigo accent
  text: "#18181b", // near-black headings/body
  muted: "#71717a", // secondary text
  danger: "#dc2626", // critical only
  success: "#16a34a",
  border: "#e4e4e7",
} as const;

const STAGE_LABELS: Record<string, string> = {
  qualified: "Qualified",
  discovery: "Discovery",
  demo: "Demo",
  proposal_sent: "Proposal sent",
  negotiation: "Negotiation",
  verbal_commit: "Verbal commit",
  closed_won: "Closed won",
  closed_lost: "Closed lost",
};

function formatCurrency(value: number): string {
  return new Intl.NumberFormat("de-DE", {
    style: "currency",
    currency: "EUR",
    maximumFractionDigits: 0,
  }).format(value);
}

function formatReason(reason: string): string {
  return reason.replaceAll("_", " ").replace(/\b\w/g, (c) => c.toUpperCase());
}

function pdfToBuffer(doc: PDFKit.PDFDocument): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    doc.on("data", (c: Buffer) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
    doc.end();
  });
}

function contentRight(doc: PDFKit.PDFDocument): number {
  return doc.page.width - doc.page.margins.right;
}

function contentWidth(doc: PDFKit.PDFDocument): number {
  return doc.page.width - doc.page.margins.left - doc.page.margins.right;
}

function addHeader(
  doc: PDFKit.PDFDocument,
  title: string,
  subtitle: string,
): void {
  doc.font("Helvetica-Bold").fontSize(20).fillColor(COLORS.primary).text("Findr");
  doc.moveDown(0.3);
  doc.font("Helvetica-Bold").fontSize(16).fillColor(COLORS.text).text(title);
  doc.font("Helvetica").fontSize(10).fillColor(COLORS.muted).text(subtitle);
  doc.moveDown(0.8);
  doc
    .strokeColor(COLORS.border)
    .lineWidth(1)
    .moveTo(doc.page.margins.left, doc.y)
    .lineTo(contentRight(doc), doc.y)
    .stroke();
  doc.moveDown(1);
}

function addFooter(doc: PDFKit.PDFDocument): void {
  const y = doc.page.height - doc.page.margins.bottom + 12;
  const date = new Date().toISOString().split("T")[0];
  doc
    .font("Helvetica")
    .fontSize(8)
    .fillColor(COLORS.muted)
    .text(
      `Generated by Findr · EU-hosted · ${date}`,
      doc.page.margins.left,
      y,
      { align: "center", width: contentWidth(doc), lineBreak: false },
    );
}

function sectionTitle(doc: PDFKit.PDFDocument, title: string): void {
  ensureSpace(doc, 40);
  doc.moveDown(0.6);
  doc.font("Helvetica-Bold").fontSize(12).fillColor(COLORS.text).text(title);
  doc.moveDown(0.4);
}

/** Add a page break if fewer than `needed` points remain before the footer. */
function ensureSpace(doc: PDFKit.PDFDocument, needed: number): void {
  const bottomLimit = doc.page.height - doc.page.margins.bottom - 20;
  if (doc.y + needed > bottomLimit) {
    doc.addPage();
  }
}

interface Column {
  label: string;
  width: number;
  align?: "left" | "right";
  color?: string;
}

/**
 * Minimal table renderer — pdfkit has no table API, so columns are positioned
 * manually. Columns are laid out left-to-right from the left margin.
 */
function renderTable(
  doc: PDFKit.PDFDocument,
  columns: Column[],
  rows: string[][],
): void {
  const left = doc.page.margins.left;
  const rowHeight = 18;

  const xFor = (index: number): number => {
    let x = left;
    for (let i = 0; i < index; i += 1) x += columns[i].width;
    return x;
  };

  // Header row
  ensureSpace(doc, rowHeight * 2);
  const headerY = doc.y;
  doc.font("Helvetica-Bold").fontSize(9).fillColor(COLORS.muted);
  columns.forEach((col, i) => {
    doc.text(col.label.toUpperCase(), xFor(i), headerY, {
      width: col.width - 8,
      align: col.align ?? "left",
      lineBreak: false,
    });
  });
  doc.y = headerY + rowHeight - 4;
  doc
    .strokeColor(COLORS.border)
    .lineWidth(0.5)
    .moveTo(left, doc.y)
    .lineTo(left + columns.reduce((s, c) => s + c.width, 0), doc.y)
    .stroke();
  doc.moveDown(0.3);

  // Data rows
  doc.font("Helvetica").fontSize(10);
  for (const row of rows) {
    ensureSpace(doc, rowHeight);
    const y = doc.y;
    columns.forEach((col, i) => {
      doc.fillColor(col.color ?? COLORS.text).text(row[i] ?? "", xFor(i), y, {
        width: col.width - 8,
        align: col.align ?? "left",
        lineBreak: false,
      });
    });
    doc.y = y + rowHeight;
  }
  doc.moveDown(0.5);
}

function keyValueRow(
  doc: PDFKit.PDFDocument,
  label: string,
  value: string,
  valueColor: string = COLORS.text,
): void {
  ensureSpace(doc, 20);
  const y = doc.y;
  doc.font("Helvetica").fontSize(11).fillColor(COLORS.muted).text(label, doc.page.margins.left, y, {
    width: 220,
    lineBreak: false,
  });
  doc
    .font("Helvetica-Bold")
    .fontSize(11)
    .fillColor(valueColor)
    .text(value, doc.page.margins.left + 220, y, {
      width: contentWidth(doc) - 220,
      lineBreak: false,
    });
  doc.y = y + 20;
}

export async function buildLossReportPdf(
  report: LossReportData,
  orgName: string,
): Promise<Buffer> {
  const doc = new PDFDocument({ size: "A4", margin: 50 });

  addHeader(
    doc,
    "Loss Analysis Report",
    `${orgName} · ${report.period_start} – ${report.period_end}`,
  );

  sectionTitle(doc, "Summary");
  keyValueRow(doc, "Total lost deals", String(report.total_lost_deals));
  keyValueRow(
    doc,
    "Total lost value",
    formatCurrency(report.total_lost_value),
    report.total_lost_value > 0 ? COLORS.danger : COLORS.text,
  );

  if (report.breakdown.length === 0) {
    doc.moveDown(1);
    doc
      .font("Helvetica")
      .fontSize(11)
      .fillColor(COLORS.muted)
      .text("No closed-lost deals in this period.");
    addFooter(doc);
    return pdfToBuffer(doc);
  }

  sectionTitle(doc, "Breakdown by reason");
  renderTable(
    doc,
    [
      { label: "Reason", width: 180 },
      { label: "Count", width: 70, align: "right" },
      { label: "Value", width: 140, align: "right" },
      { label: "Share", width: 70, align: "right" },
    ],
    report.breakdown.map((b) => [
      formatReason(b.reason),
      String(b.count),
      formatCurrency(b.value),
      `${Math.round(b.percentage)}%`,
    ]),
  );

  if (report.top_lost_companies.length > 0) {
    sectionTitle(doc, "Top lost opportunities");
    renderTable(
      doc,
      [
        { label: "Company", width: 240 },
        { label: "Value", width: 130, align: "right" },
        { label: "Reason", width: 130, align: "right" },
      ],
      report.top_lost_companies.map((c) => [
        c.name,
        formatCurrency(c.value),
        formatReason(c.reason),
      ]),
    );
  }

  const reasonsWithQuotes = report.breakdown.filter(
    (b) => b.sample_quotes.length > 0,
  );
  if (reasonsWithQuotes.length > 0) {
    sectionTitle(doc, "Sample evidence");
    for (const b of reasonsWithQuotes) {
      ensureSpace(doc, 40);
      doc
        .font("Helvetica-Bold")
        .fontSize(10)
        .fillColor(COLORS.text)
        .text(formatReason(b.reason));
      doc.moveDown(0.2);
      for (const quote of b.sample_quotes.slice(0, 2)) {
        ensureSpace(doc, 30);
        doc
          .font("Helvetica-Oblique")
          .fontSize(9)
          .fillColor(COLORS.muted)
          .text(`“${quote}”`, {
            width: contentWidth(doc),
            indent: 10,
          });
        doc.moveDown(0.2);
      }
      doc.moveDown(0.4);
    }
  }

  addFooter(doc);
  return pdfToBuffer(doc);
}

function winProbabilityColor(prob: number): string {
  if (prob >= 75) return COLORS.success;
  if (prob < 25) return COLORS.danger;
  return COLORS.text;
}

export async function buildForecastPdf(
  forecast: ForecastSummary,
  orgName: string,
): Promise<Buffer> {
  const doc = new PDFDocument({ size: "A4", margin: 50 });

  addHeader(
    doc,
    "Pipeline Forecast",
    `${orgName} · Generated ${new Date().toISOString().split("T")[0]}`,
  );

  sectionTitle(doc, "Scenarios");
  keyValueRow(doc, "Best case", formatCurrency(forecast.best_case), COLORS.success);
  keyValueRow(doc, "Likely case", formatCurrency(forecast.likely_case), COLORS.primary);
  keyValueRow(doc, "Worst case", formatCurrency(forecast.worst_case));

  sectionTitle(doc, "Pipeline summary");
  keyValueRow(
    doc,
    "Total pipeline value",
    formatCurrency(forecast.total_pipeline_value),
  );
  keyValueRow(
    doc,
    "Weighted pipeline value",
    formatCurrency(forecast.weighted_pipeline_value),
    COLORS.primary,
  );
  keyValueRow(
    doc,
    "Deals at-risk value",
    formatCurrency(forecast.deals_at_risk_value),
    forecast.deals_at_risk_value > 0 ? COLORS.danger : COLORS.text,
  );
  keyValueRow(doc, "Open deals", String(forecast.open_deal_count));

  if (forecast.open_deal_count === 0) {
    doc.moveDown(1);
    doc
      .font("Helvetica")
      .fontSize(11)
      .fillColor(COLORS.muted)
      .text("No open deals in the pipeline.");
    addFooter(doc);
    return pdfToBuffer(doc);
  }

  if (forecast.by_stage.length > 0) {
    sectionTitle(doc, "By stage");
    renderTable(
      doc,
      [
        { label: "Stage", width: 170 },
        { label: "Count", width: 60, align: "right" },
        { label: "Value", width: 140, align: "right" },
        { label: "Weighted", width: 90, align: "right" },
      ],
      forecast.by_stage.map((s) => [
        STAGE_LABELS[s.stage] ?? formatReason(String(s.stage)),
        String(s.count),
        formatCurrency(s.value),
        formatCurrency(s.weighted),
      ]),
    );
  }

  const topDeals = forecast.forecasts.slice(0, 10);
  if (topDeals.length > 0) {
    sectionTitle(doc, "Top deals by weighted value");
    renderTable(
      doc,
      [
        { label: "Deal", width: 170 },
        { label: "Stage", width: 90 },
        { label: "Amount", width: 90, align: "right" },
        { label: "Win %", width: 50, align: "right" },
        { label: "Weighted", width: 70, align: "right" },
      ],
      topDeals.map((d) => [
        d.deal_name,
        STAGE_LABELS[d.stage] ?? formatReason(String(d.stage)),
        formatCurrency(d.amount),
        `${Math.round(d.win_probability)}%`,
        formatCurrency(d.weighted_value),
      ]),
    );

    // Win-probability legend with colors (kept simple — colors applied to the
    // legend dots, table cells stay neutral for print legibility).
    doc.moveDown(0.2);
    const legendY = doc.y;
    const legend: Array<{ label: string; color: string }> = [
      { label: ">= 75% likely", color: winProbabilityColor(80) },
      { label: "< 25% at risk", color: winProbabilityColor(10) },
    ];
    let lx = doc.page.margins.left;
    doc.font("Helvetica").fontSize(8);
    for (const item of legend) {
      doc.circle(lx + 3, legendY + 4, 3).fill(item.color);
      doc.fillColor(COLORS.muted).text(item.label, lx + 12, legendY, {
        lineBreak: false,
        width: 120,
      });
      lx += 140;
    }
    doc.y = legendY + 16;
  }

  addFooter(doc);
  return pdfToBuffer(doc);
}
